### ISSUE TITLE
jobperf fails if PBS is installed in a directory other than /opt/pbs/default/bin

### ISSUE THREAD

**Issue by ndusek** [clemsonciti/jobperf#1]
In `qstat.go`, the functions `qstatGetJob()` and `QSelectJobs()` both assume the PBS `bin` directory is located at `/opt/pbs/default/bin`. 

In order to accommodate cases where PBS may be installed in an alternative location, it would be great if `jobperf` could use the location specified by `PBS_EXEC` environment variable, which should be available in most installations of PBS Pro. If not, another option would be to specify an alternative executable path via an optional command line flag.

**Comment by dougnd** [comment]
It was great to talk to you at PEARC!  This is a good point, we probably shouldn't hardcode paths.  I've pushed a change in v0.0.5 where it uses the suggestion of `exec.LookPath()`, could you see if it works for you?

**Comment by ndusek** [comment]
Great talking with you too.

I just tested the generic pre-compiled executable for v0.0.5 on our two different clusters and I got the same error on both.

**Bright cluster:**

```
time=2024-07-25T14:41:07.017-05:00 level=ERROR msg="Failed to get job" err="failed to run qstat for job id 628006: fork/exec /cm/shared/apps/openpbs/current/bin/qstat/qstat: not a directory"
```

**OpenHPC cluster:**

```
time=2024-07-25T14:42:35.023-05:00 level=ERROR msg="Failed to get job" err="failed to run qstat for job id 18939: fork/exec /opt/pbs/bin/qstat/qstat: not a directory"
```

So it looks like you maybe went one level further than you needed to with the path?

**Comment by dougnd** [comment]
Whoops, yes thank you.  And it looks like when I uploaded it to our PBS cluster to test, I didn't properly make sure I was calling the new binary.  Please try v0.0.6.

**Comment by ndusek** [comment]
Great, thanks! I can confirm that this issue is fixed in v0.0.6.

I am getting another error now (`failed to read private key`) but I see that you have a TODO for that one:

```
// TODO: better home folder resolution: spack and root don't use /home/username.
```

So I'm going to close this one as resolved. Thanks again!

**Comment by dougnd** [comment]
Ah.  Try v0.0.7.  I've updated that bit of code to use user.Lookup(...) to fetch the user information.  It seems to work on Palmetto, but it may depend on how your home directories and user information is configured.

**Comment by ndusek** [comment]
Ok, I no longer get the error complaining about missing private keys, but now I get two different errors (one on each of our different clusters).

**Bright cluster:**

```
time=2024-07-26T08:27:53.199-05:00 level=INFO msg="failed to update node stats: failed to connect to node cmp0019 with ssh: failed to dial host cmp0019: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain"
```

In the above case, I am able to login to the node using `ssh cmp0019` using public key authentication, so that's interesting. But SSH to our compute nodes in our Bright cluster is slow sometimes, so maybe it's a delayed response time issue?

**OpenHPC cluster:**

```
time=2024-07-26T08:30:31.445-05:00 level=INFO msg="failed to update node stats: failed to decode cpu/mem response from node stats: EOF"
```

Here, it looks like the SSH succeeded but there was some issue parsing the output returned.

I'm starting to suspect that our environment is weird in a number of ways compared to other clusters, so don't feel like you have to run down and patch all these errors. I'm happy to keep providing testing and feedback as long you like, but I can also hack away at it myself and submit a PR if desired.

**Comment by dougnd** [comment]
Yeah, we may be hitting the end of the easy to fix stuff, but I'm happy to accept PRs and bounce ideas back and forth.

## Bright cluster

I'm not seeing much left that feels very Palmetto specific with the SSH implementation.  The last thing to check would be to see if the file ".ssh/id_rsa" exists in your home directory.   It is possible you are using something other than RSA keys.  You might have a ".ssh/id_ed25519" file instead.  Of course, I'd expect a different error then...

If it was a timeout issue, I'd expect a different error, but maybe? My reading of [ssh.ClientConfig docs ](https://pkg.go.dev/golang.org/x/crypto/ssh#ClientConfig) is that by default there is no TCP timeout.

## OpenHPC

This looks easier to fix.  My guess is that your cgroups are on a different path.  The current code assumes you can fetch cgroup information from `/sys/fs/cgroup/pbspro.service/jobid/<jobid>` (see: https://github.com/clemsonciti/jobperf/blob/main/cmd/jobperf/nodestats.go#L78).  If you login to a compute node while the job is running perhaps you'll find the cgroup in another path?
