### ISSUE TITLE
adapt to changing squeue json format

### ISSUE THREAD

**Issue by elelayan** [clemsonciti/jobperf#4]
Hi, on slurm 24.05.1 (data_parser/v0.0.41) the squeue json format changed: 
1. `nodes` is not a string anymore but a structure. This breaks parsing
2. we find what used to be `allocated_nodes` in `nodes.allocation`, with a change in core allocation status format (even unallocated cores are reported and we need to check their status to know if we should include them in the count).

I first wrote a draft version of the code to make it work in my case but I'll submit backward-compatible code in a PR

**Comment by dougnd** [comment]
Yep, we were running into this too as we worked on updating our cluster.  I've just pushed a change set that I believe fixes it. Try the v0.1.0 release.  PRs definitely appreciated if we missed something or if there's a cleaner way to do things.

**Comment by elelayan** [comment]
Cool, thanks!
I was getting into ugly code with json.RawMessage, then filling the new nodes structure from existing.
Your code is better. And it works :+1:
